Repository cirosec-studis/python-zimbra-web, pull requests merged in 2021-11, with the labels that each got.

#34 Release v1.1
  .gitignore
  MANIFEST.in
  README.md
  src/zimbra/__init__.py
  src/zimbra/templates/message.txt
  tests/conftest.py
  tests/templates/Testbild.jpg
  tests/templates/unicode.txt
  tests/test_zimbra.py
  tox.ini
Labels: release

#47 Automatically buid documentation using Sphinx
  .github/workflows/tests.yml
Labels: documentation

#54 Feature emlparsing
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
  tests/templates/attachmentmail.eml
  tests/templates/outlookmail.eml
  tests/templates/simplemail.eml
  tests/test_zimbra.py
Labels: enhancement

#61 Refactor EML parsing
  README.md
  docs/source/index.rst
  docs/source/zimbraweb.rst
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
  tests/templates/attachmentmail.eml
  tests/templates/attachments.eml
  tests/templates/html.eml
  tests/templates/outlookmail.eml
  tests/templates/plaintext.eml
  tests/templates/simplemail.eml
  tests/test_zimbra.py
Labels: enhancement

#58 Release v2.0
  .github/workflows/tests.yml
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/zimbraweb.rst
  pyproject.toml
  requirements_dev.txt
  setup.cfg
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
  tests/conftest.py
  tests/templates/attachments.eml
  tests/templates/html.eml
  tests/templates/plaintext.eml
  tests/test_zimbra.py
Labels: release

#64 Hotfix: Broken documentation link in README
  README.md
  src/zimbraweb/__init__.py
Labels: bug

#67 Hotfix 2.0.2
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
Labels: bug

#68 Hotfixes 2.0
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
Labels: bug

#70 Strip newlines from headers
  src/zimbraweb/__init__.py
  src/zimbraweb/emlparsing.py
Labels: bug
